version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: traffic_flow_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: traffic_flow
      MYSQL_USER: traffic_user
      MYSQL_PASSWORD: traffic_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
